services:
  nginx:
    image: nginx:1.17
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8000:80"
    depends_on:
      - backend
      - frontend

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/home/node/app
      - /home/node/app/node_modules
    environment:
      - NODE_ENV=development
      - WDS_SOCKET_PORT=0
    expose:
      - "3000"
    command: "npm start"

  backend:
    image: todo-app/backend
    build: ./backend
    volumes:
      - ./backend:/usr/src/app
    expose:
      - "3001"
    ports:
      - "8001:3001"
    command: "python src/server.py"
    environment:
      - DEBUG=true
    env_file:
      - .env
